### ISSUE TITLE
Searching a profile 

### ISSUE THREAD

**Issue by krishnanandula** [streatbeat/simba#15]
https://github.com/streatbeat/simba/issues/2

@RaviAchanti consider the following

1. when there are no search results display a message, "no records found"
2. can we include the profile picture into the search results ?
3. can we do a cross search or full text search like ".net 8 years of experience" , "hyderabad java 7years of experience".

Search is the one major feature for the complete project, we need these searching capabilities to make use of the product.

**Comment by krishnanandula** [comment]
@RaviAchanti ;

Point 3 - yet to be worked up on , rest all are good.

**Comment by RaviAchanti** [comment]
Pushed Point 3 as well. Not so efficient method but will work giving search text

**Comment by krishnanandula** [comment]
@subhakamesh , Please test this.
