### ISSUE TITLE
Unable to login or register a user - Database Issue

### ISSUE THREAD

**Issue by subhakamesh** [streatbeat/simba#7]
> Unable to update database to match the current model because there are pending changes and automatic migration is disabled. Either write the pending model changes to a code-based migration or enable automatic migration. Set DbMigrationsConfiguration.AutomaticMigrationsEnabled to true to enable automatic migration.

**Comment by subhakamesh** [comment]
Steps to Solve:

Change the connection string(DefaultConnection) according to your local sql server connection in WEB.Config.

In Packager-Manager Console -
1. Install-Package EntityFramework -IncludePrerelease
2. enable-migrations
3. add-migration "pending changes"
4. update-database

**Comment by krishnanandula** [comment]
Resolved.
