### ISSUE TITLE
Profile Picture - Upload

### ISSUE THREAD

**Issue by subhakamesh** [streatbeat/simba#8]
Restrict the user to upload picture of default size.

Currently if a user uploads a profile picture of different width and height ; the UI elements on the page misaligned.

![image](https://cloud.githubusercontent.com/assets/8253768/16960025/8f9490e2-4d9c-11e6-8d3c-b77b89a7a4e3.png)

**Comment by krishnanandula** [comment]
Fixed , please get the latest of master and re-check.

**Comment by subhakamesh** [comment]
Bug Fixed, closed.
