### ISSUE TITLE
Picture Visibility issue 

### ISSUE THREAD

**Issue by subhakamesh** [streatbeat/simba#9]
Picture upload is not user friendly, there is no clear to understand weather upload option is there or not

![image](https://cloud.githubusercontent.com/assets/8253768/16961212/6331b94e-4da1-11e6-8814-8ced1f22ff73.png)

**Comment by krishnanandula** [comment]
Fixed , please get the latest of master and re-check.

**Comment by subhakamesh** [comment]
Bug fixed closed
